### ISSUE TITLE
Possible incorrect information on the backwards incompatible changes pages

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1559]
Feedback on page: [/guides/v2.2/release-notes/changes/ce_changes.html](http://devdocs.magento.com/guides/v2.2/release-notes/changes/ce_changes.html)

I was looking into making one of our modules compatible with Magento 2.2.x and went through the list of classes which changed between 2.1.9 and 2.2.0, and noticed a class which is stated as `Class was added` even though the class already existed in 2.1.9.

The class I'm talking about is `Magento\Config\Model\Config\Source\Yesno`
It exists in both [Magento 2.1.9](https://github.com/magento/magento2/blob/2.1.9/app/code/Magento/Config/Model/Config/Source/Yesno.php) and in [Magento 2.2.0](https://github.com/magento/magento2/blob/2.2.0/app/code/Magento/Config/Model/Config/Source/Yesno.php)

I'm now a little bit worried that this page might contain incorrect information and I shouldn't rely on it.
Can someone confirm if this page has been generated correctly and recheck the script which generates this to see why this happened?

Thanks!

_UPDATE_, just by going through some more classes we use in our module, I find even more occurrences of the same problem:

- `Magento\Config\Model\Config\Structure\Element\Dependency\FieldFactory`
- `Magento\Config\Model\Config\Source\Locale\Country`
- `Magento\Config\Model\Config\Source\Locale\Weekdays`
- `Magento\Config\Model\Config\Source\Email\Template`
- `Magento\Cms\Model\Wysiwyg\Config`
- `Magento\Eav\Model\Entity\Attribute`
- `Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface`
- `Magento\Eav\Block\Adminhtml\Attribute\Grid\AbstractGrid`
- `Magento\Eav\Model\Entity\Attribute`
- ...

**Comment by dshevtsov** [comment]
@hostep thanks for your feedback!
Will check.

**Comment by hostep** [comment]
And another discrepancy, just ran into a class we used in 2.1.9, but that class no longer exist in 2.2.0, and it isn't mentioned on the backwards incompatible changes document:
- `Magento\Eav\Model\Entity\AttributeCache`

**Comment by dshevtsov** [comment]
Created internal issue MAGEDOC-2632

**Comment by dshevtsov** [comment]
After internal discussion we decided to remove sections that contain changes between minor releases of different patch versions 2.0.x-2.1.0, 2.1.y-2.2.0. Reasons:
1. The tool makes mistakes
2. Considering the semantic versioning policy, more sense makes publishing changes between GAs of minor releases like 2.0.0-2.1.0 and 2.1.0-2.2.0

There is a strong possibility that we will publish changes between 2.0.0-2.1.0 and 2.1.0-2.2.0 soon.

**Comment by hostep** [comment]
Hmm, I don't know, it feels wrong to remove the list of changes between minor versions.
Even though, in a perfect world, there won't be Backwards Incompatible changes between minor versions, but we all know that Magento's world currently isn't really perfect, so BI changes will still happen I'm afraid, even in minor releases.
And it would still be nice to view these BI changes somewhere.

**Comment by dshevtsov** [comment]
I merged update with tables that show changes between minor releases (2.x.0-2.y.0) and a warning that describes the temporary issue.

**Comment by hostep** [comment]
Ok thanks, I already suspected the problems were caused by the docblock tags.
Good that it is mentioned now as a temporary notice.

There's a small typo in there btw: `addedd` should be `added` ;)

**Comment by dshevtsov** [comment]
@hostep thanks!
Fixed the typo

**Comment by jcalcaben** [comment]
This issue has been addressed. Please create a new issue if this problem reappears.

**Comment by dshevtsov** [comment]
The issue still exists, we just added a note that warns about it.

**Comment by dshevtsov** [comment]
The ticket for engineering is MAGETWO-86853.
