### ISSUE TITLE
Incorrect release notes for 2.3.5

### ISSUE THREAD

**Issue by MichaelThessel** [magento/devdocs#7779]
# Bug report

## Description

The [2.3.5 release notes](https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-5-open-source.html#customer) contain this section:

```
You can now successfully create a customer and associate it with a particular website using the Associate to Website dropdown menu on Customers > All Customers > Add new Customer. Previously, when you tried to associate a new customer with the non-default website in a multi-site deployment, Magento displayed this error: The store view is not in the associated website.
```

The same paragraph is contained in the [2.4 release notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html#customer).

This has not been fixed in 2.3.5 and probably only was addressed in 2.4

## Expected result

Remove section from 2.3.5 release notes.

**Comment by jfrontain** [comment]
Thanks for reading the 2.3.5 release notes so attentively, @MichaelThessel. Our PM has investigated and confirms that this fix was merged into 2.3.5, so I am leaving the issue description in the notes. Closing.

**Comment by MichaelThessel** [comment]
@jfrontain strange. I'm seeing the issue still in 2.3.5-p2. That's why I came across this in the fist place. I don't think that has been packported to 2.3.5. Can you double check with your PM and make sure that this code has actually made it into 2.3.5?

**Comment by krisztian-fekete** [comment]
@jfrontain This is definitely not fixed, having the same issue on 2.3.5-p2:

![magento_bug](https://user-images.githubusercontent.com/14894040/94253178-38cc3000-ff25-11ea-9da4-593b3c68a133.png)

**Comment by MichaelThessel** [comment]
@krisztian-fekete I temporarily fixed it via a composer patch:

```
--- a/vendor/magento/module-customer/Controller/Adminhtml/Index/Save.php
+++ b/vendor/magento/module-customer/Controller/Adminhtml/Index/Save.php
@@ -322,11 +322,16 @@
 
                 if (isset($customerData['sendemail_store_id']) && $customerData['sendemail_store_id'] !== false) {
                     $customer->setStoreId($customerData['sendemail_store_id']);
+                    try {
+                        $this->customerAccountManagement->validateCustomerStoreIdByWebsiteId($customer);
+                    } catch (LocalizedException $exception) {
+                        throw new LocalizedException(__("The Store View selected for sending Welcome email from".
+                            " is not related to the customer's associated website."));
+                    }
                 }
 
                 // Save customer
                 if ($customerId) {
-                    $this->customerAccountManagement->validateCustomerStoreIdByWebsiteId($customer);
                     $this->_customerRepository->save($customer);
 
                     $this->getEmailNotification()->credentialsChanged($customer, $currentCustomer->getEmail());
```

```
{
    ...
    "extra": {
        "magento-force": "override",
        "composer-exit-on-patch-failure": true,
        "patches": {
            "magento/module-customer": {
                "Patch for issue 226 (cannot create customer for non-default website; issue will be resolved in 2.4)": "patches/composer/issue-ac226.diff"
            }
        }
    }
}
```

**Comment by hostep** [comment]
@jfrontain: I can confirm @MichaelThessel's findings, we also had to create a patch to fix this problem in Magento 2.3.5, so it was definitely not fixed in that version. I seem to remember that I too was confused by the line in the 2.3.5 release notes, it's not correct I believe. It was fixed by ticket `MC-30650` from the information I can find in our patches repository.
